### ISSUE TITLE
Is story active?

### ISSUE THREAD

**Issue by rootkea** [xaprb/story#102]
Hello,

I'm sorry for the title of the issue but since the last commit was a year ago and the PRs have been pending for a long time it compelled me to open this issue.

I really like story! And I hope it picks up the development again. :) If not, then is there an active story fork being maintained? I really don't want to use other Hugo theme over story.

Thank you!

**Comment by tchinchow** [comment]
I can't consider myself actively participating to this dev...

However, to whom it may concern : I did fork the project and I am currently working on a few things:
- Fixing a few things that broke when Hugo's markdown engine switched to Goldmark
- Adding MermaidJS shortcodes

I have also added a few other features such like:
- Embedded images carousel/slideshows with "`flexslider-js`"
- Embedded videos with "`video-js`"
- Maps and GPX tracks with "`leaflet-js`"
- Keyboard keys rendering (if you need to emphasis on a shortcut for instance)

I did not propose pull-requests because I feel like I may have gone a little out of line with the minimalistic nature of Story.

I also did not use the slides feature as much as I expected _(but it is a great feature of Story)_ and therefore, I did not make sure that some of the above feature _(mermaid, etc...)_ properly render in "`remark-js`".

As usual in OSS, everything is proposed as-is : I can not guarantee that I'll actively work on this and I'm not proposing to become a maintainer.

**Comment by xaprb** [comment]
I have not been actively developing or even monitoring PRs/issues. Since several people seem to be interested in doing that, please feel free to develop one of the forks or similar, or propose a way that you could work on the project if you prefer something else. I don't mind if others work on it, I simply don't have time or interest to do that myself.

**Comment by xaprb** [comment]
I’m sorry but I’m not interested in maintaining this theme anymore. I’m glad it’s been useful, and I encourage someone to continue development elsewhere. The MIT license is very permissive and should not place any burdensome restrictions upon that.
